const state={documents:[],editor:null,pdfs:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=m=>{let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600)};
async function api(url,opts={}){const r=await fetch(url,opts);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function page(name){$$('.page').forEach(x=>x.classList.toggle('active',x.id===name));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===name))}
$$('.nav').forEach(x=>x.onclick=()=>page(x.dataset.page));
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function loadLibrary(){state.documents=await api('/api/documents');const el=$('#library');el.innerHTML='';if(!state.documents.length){el.innerHTML='<div class="doc-card"><h3>No documents yet</h3><p>Create a document or open a file to begin.</p></div>';return}state.documents.forEach(d=>{const c=document.createElement('article');c.className='doc-card';c.innerHTML=`<div><h3>${escapeHtml(d.name)}</h3><p>${d.fileType.toUpperCase()} · ${new Date(d.updatedAt).toLocaleString()}</p></div><div class="card-actions"><button data-open="${d.id}">Open</button><button class="secondary" data-delete="${d.id}">Delete</button></div>`;el.append(c)});el.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openEditor(b.dataset.open));el.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this document?')){await api('/api/documents/'+b.dataset.delete,{method:'DELETE'});loadLibrary()}})}
function loadScript(src){return new Promise((resolve,reject)=>{if(document.querySelector(`script[src="${src}"]`))return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(Error('Could not load ONLYOFFICE. Start Document Server first.'));document.head.append(s)})}
async function openEditor(id){page('editor');const d=state.documents.find(x=>x.id===id);$('#editorTitle').textContent=d?.name||'Document Editor';$('#onlyoffice').innerHTML='<div style="padding:30px">Loading ONLYOFFICE…</div>';try{const data=await api('/api/onlyoffice/config/'+id);await loadScript(data.onlyofficeUrl+'/web-apps/apps/api/documents/api.js');$('#onlyoffice').innerHTML='<div id="ooEditor" style="width:100%;height:100%"></div>';state.editor=new DocsAPI.DocEditor('ooEditor',data.config)}catch(e){$('#onlyoffice').innerHTML=`<div style="padding:30px"><strong>ONLYOFFICE is not available.</strong><p>${escapeHtml(e.message)}</p><p>Start it with <code>docker compose -f docker-compose.onlyoffice.yml up -d</code>.</p></div>`}}
$('#closeEditor').onclick=()=>{state.editor?.destroyEditor();state.editor=null;page('documents');loadLibrary()};
$('#newDoc').onclick=async()=>{try{const d=await api('/api/documents/new',{method:'POST'});await loadLibrary();openEditor(d.id)}catch(e){toast(e.message)}};
$('#upload').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const b=await toBase64(f),ext=f.name.split('.').pop().toLowerCase();const d=await api('/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.name,fileType:ext,base64:b})});e.target.value='';await loadLibrary();openEditor(d.id)}catch(err){toast(err.message)}};
function toBase64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(file)})}
$('#pdfInput').onchange=e=>{for(const f of e.target.files)state.pdfs.push(f);e.target.value='';renderPdfBoard()};
function renderPdfBoard(){const board=$('#pdfBoard');board.innerHTML='';if(!state.pdfs.length){board.classList.add('empty');board.textContent='Add PDF files to begin.';return}board.classList.remove('empty');state.pdfs.forEach((f,i)=>{const card=document.createElement('div');card.className='pdf-card';card.innerHTML=`<div class="preview">PDF ${i+1}</div><strong>${escapeHtml(f.name)}</strong><div class="pdf-actions"><button data-up="${i}">↑</button><button data-down="${i}">↓</button><button data-del="${i}">Delete</button></div>`;board.append(card)});board.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>movePdf(+b.dataset.up,-1));board.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>movePdf(+b.dataset.down,1));board.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.pdfs.splice(+b.dataset.del,1);renderPdfBoard()})}
function movePdf(i,d){const j=i+d;if(j<0||j>=state.pdfs.length)return;[state.pdfs[i],state.pdfs[j]]=[state.pdfs[j],state.pdfs[i]];renderPdfBoard()}
$('#clearPdf').onclick=()=>{state.pdfs=[];renderPdfBoard()};
$('#mergePdf').onclick=async()=>{if(!state.pdfs.length)return toast('Add PDFs first');try{const out=await PDFLib.PDFDocument.create();for(const f of state.pdfs){const src=await PDFLib.PDFDocument.load(await f.arrayBuffer());const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}const bytes=await out.save(),blob=new Blob([bytes],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='TUBOL-Merged.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Merged PDF downloaded')}catch(e){toast(e.message)}};
loadLibrary();
